on: [push, pull_request]
name: CI
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: '>=1.19.0'
          cache: true
      - run: go version

    # TESTS

    # Run all tests
    - name: Test
      run: go test -v -race ./...

    # TEST COVERAGE

    - name: Calculate coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
